import PDFDocument from 'pdfkit';
import { AchievementModel } from '../models/achievement.model';
import { UserModel } from '../models/user.model';
import { LeaderboardEntry } from '../models/kpi.model';

export async function generateAchievementReport(userId: number): Promise<Buffer> {
  const user = UserModel.findById(userId);
  const achievements = AchievementModel.findByUser(userId);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(20).text('Achievement Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(user ? user.name : `User #${userId}`, { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).text(`Generated: ${new Date().toISOString().slice(0, 10)}`, { align: 'center' });
    doc.moveDown(2);

    // Achievements list
    if (achievements.length === 0) {
      doc.fontSize(12).text('No achievements recorded yet.');
    } else {
      for (const achievement of achievements) {
        doc.fontSize(12).font('Helvetica-Bold').text(achievement.title);
        if (achievement.description) {
          doc.fontSize(10).font('Helvetica').text(achievement.description);
        }
        doc.fontSize(9).font('Helvetica').fillColor('#666').text(`Awarded: ${achievement.awarded_at}`);
        doc.moveDown();
      }
    }

    doc.end();
  });
}

export async function generateKpiReport(leaderboard: LeaderboardEntry[], semesterName: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text(`KPI Report — ${semesterName}`, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
      .text(`Generated: ${new Date().toISOString().slice(0, 10)}`, { align: 'center' });
    doc.moveDown(1.5);

    // Column layout
    const colX = [50, 120, 250, 320, 390, 460, 510];
    const headers = ['Rank', 'Club', 'Dept', 'Attend.', 'Achiev.', 'Members', 'Score'];

    doc.fillColor('#000').fontSize(9).font('Helvetica-Bold');
    headers.forEach((h, i) => doc.text(h, colX[i], doc.y, { width: colX[i + 1] ? colX[i + 1] - colX[i] - 5 : 60, continued: i < headers.length - 1 }));
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(0.4);

    for (const [idx, club] of leaderboard.entries()) {
      // Highlight top 3
      if (club.rank <= 3) {
        const medal = club.rank === 1 ? '#FFD700' : club.rank === 2 ? '#C0C0C0' : '#CD7F32';
        doc.rect(45, doc.y - 2, 520, 14).fillColor(medal).fillOpacity(0.15).fill();
        doc.fillOpacity(1);
      }

      const y = doc.y;
      doc.fillColor('#000').fontSize(9).font(club.rank <= 3 ? 'Helvetica-Bold' : 'Helvetica');
      const cells = [
        String(club.rank),
        club.club_name.slice(0, 18),
        (club.department ?? '—').slice(0, 10),
        String(club.attendance_count),
        String(club.achievement_count),
        String(club.member_count),
        String(club.total_score),
      ];
      cells.forEach((c, i) => {
        doc.text(c, colX[i], y, { width: colX[i + 1] ? colX[i + 1] - colX[i] - 5 : 60, continued: i < cells.length - 1 });
      });
      doc.moveDown(0.5);

      // Separator every row
      if (idx < leaderboard.length - 1) {
        doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#eee').stroke();
        doc.moveDown(0.2);
      }
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999').text('Generated by CMP — Clubs Management Platform', { align: 'center' });

    doc.end();
  });
}
